name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          SQLALCHEMY_DATABASE_URL: "sqlite:///:memory:"
          ENCRYPTION_SECRET_KEY: sycretkey_testenv
          ENCRYPTION_ALGORITHM: HS256
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: pytest
